2024-12-27 16:33:40,710 ERROR: Exception on /detail/page [GET] [in D:\IT\Local_Code_Path\Manage_System\house_customized_app\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "D:\IT\Local_Code_Path\Manage_System\house_customized_app\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IT\Local_Code_Path\Manage_System\house_customized_app\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IT\Local_Code_Path\Manage_System\house_customized_app\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IT\Local_Code_Path\Manage_System\house_customized_app\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IT\Local_Code_Path\Manage_System\house_customized_app\src\controller\api\backend\house_detail_api.py", line 39, in find_house_detail_by_pages
    return result
                  
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2024-12-27 16:34:07,433 ERROR: Exception on /detail/page [GET] [in D:\IT\Local_Code_Path\Manage_System\house_customized_app\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "D:\IT\Local_Code_Path\Manage_System\house_customized_app\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IT\Local_Code_Path\Manage_System\house_customized_app\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IT\Local_Code_Path\Manage_System\house_customized_app\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IT\Local_Code_Path\Manage_System\house_customized_app\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IT\Local_Code_Path\Manage_System\house_customized_app\src\controller\api\backend\house_detail_api.py", line 39, in find_house_detail_by_pages
    return result
                  
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2024-12-27 16:34:14,352 ERROR: Exception on /detail/page [GET] [in D:\IT\Local_Code_Path\Manage_System\house_customized_app\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "D:\IT\Local_Code_Path\Manage_System\house_customized_app\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IT\Local_Code_Path\Manage_System\house_customized_app\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IT\Local_Code_Path\Manage_System\house_customized_app\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IT\Local_Code_Path\Manage_System\house_customized_app\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IT\Local_Code_Path\Manage_System\house_customized_app\src\controller\api\backend\house_detail_api.py", line 38, in find_house_detail_by_pages
    result = details_service.get_details_by_page(int(page_index), int(page_size))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IT\Local_Code_Path\Manage_System\house_customized_app\src\service\details_service.py", line 24, in get_details_by_page
    print(details_list)
UnicodeEncodeError: 'gbk' codec can't encode character '\xb2' in position 35: illegal multibyte sequence
